[versions]
billing-ktx = "7.1.1"
kotlin = "2.1.21"
colorpicker-compose = "1.1.2"
filekit = "0.10.0-beta04"
kotlinx-coroutines-core = "1.8.0"
kotlinx-coroutines-test = "1.8.0"
play-services-ads = "24.3.0"
sqldelight = "2.0.2"
agp = "8.6.0"
revenuecat = "2.0.0+15.0.0"
turbine = "1.2.0"
mockk = "1.13.14"

# compose
compose = "1.8.0"
compose-multiplatform = "1.8.1"
compose-compiler = "2.1.0"

# server
ktor = "3.0.0"

google-services = "4.4.3"
detekt = "1.23.8"
kotlinx-serialization = "1.6.3"
kotlinx-datetime = "0.6.1"
app-update = "2.1.0"

appcompat = "1.7.0"
uuid = "0.8.1"
firebase-crashlytics-gradle = "3.0.2"

lexilabs-basic = "2.6.0"

[libraries]
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billing-ktx" }
colorpicker-compose = { module = "com.github.skydoves:colorpicker-compose", version.ref = "colorpicker-compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose" }

revenuecat-core = { module = "com.revenuecat.purchases:purchases-kmp-core", version.ref = "revenuecat" }
revenuecat-datetime = { module = "com.revenuecat.purchases:purchases-kmp-datetime", version.ref = "revenuecat" }
revenuecat-ui = { module = "com.revenuecat.purchases:purchases-kmp-ui", version.ref = "revenuecat" }

filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }

kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "app-update" }
app-update = { module = "com.google.android.play:app-update", version.ref = "app-update" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }

# Ktor server (Multiplatform)
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-double-receive = { module = "io.ktor:ktor-server-double-receive", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Ktor client (Multiplatform)
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

# Ktor server platform-specific engines
ktor-server-cio-jvm = { module = "io.ktor:ktor-server-cio-jvm", version.ref = "ktor" }
ktor-server-jetty = { module = "io.ktor:ktor-server-jetty-jvm", version.ref = "ktor" }
ktor-server-js = { module = "io.ktor:ktor-server-js", version.ref = "ktor" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose-compiler" }

kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-gradle" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

buildkonfig = { id = "com.codingfeline.buildkonfig", version.strictly = "0.17.1" }

sentry = { id = "io.sentry.kotlin.multiplatform.gradle", version.strictly = "0.13.0" }
